# Generated by Django 3.2 on 2021-04-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_owner_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='oname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='owner',
            name='pwd',
            field=models.CharField(max_length=40),
        ),
    ]
